version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/book_recommendation
      - SECRET_KEY=${SECRET_KEY}

volumes:
  mongo_data:
