on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master"]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to run the workflow'
        required: true
        default: 'docker_added'
        options:
          - master
          - docker_added

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v4
    - name: Install Ruff
      run: |
        pip install ruff

    - name: Run Ruff linter
      run: |
        ruff check . 
        
    - name: Install Black
      run: |
        pip install black

    - name: Run Black linter
      run: |
        black . 
        
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
    - name: Run docker-compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "./docker-compose.yml"

    - name: Wait for services to be ready
      run: sleep 30  

    - name: Execute tests in the running services
      run: docker-compose run app python -m unittest tests/tests.py

    - name: Stop and remove Docker containers
      if: always()
      run: docker-compose down
