jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: |
          docker build -t book_recommendation-app .
      - name: Install dependencies
        run: |
          docker run book_recommendation-app pip install -r requirements.txt
      - name: Run Black
        run: |
          docker run book_recommendation-app black .
      - name: Run Ruff
        run: |
          docker run book_recommendation-app ruff check
      - name: Run tests
        run: |
          docker run book_recommendation-app python -m unittest discover tests

